exports.react = require('react')
exports['react-dom'] = require('react-dom')
exports['react-redux'] = require('react-redux')
exports['react-router-dom'] = require('react-router-dom')
exports['redux'] = require('redux')
exports.classnames = require('classnames')
